version: '3.8'

services:

  rabbitmq: # broker service from default image https://hub.docker.com/_/rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:latest 
    hostname: 'rabbitmq'
    container_name: 'rabbitmq' 
    ports: 
        - 5672:5672   # normal communication
        - 15672:15672 # web interface
    networks:
      - backend # connected networks

  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=userdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend # connected networks

  tripservice:
    build:
      context: .
      dockerfile: ./TripService/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=tripdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend # connected networks

  flightservice:
    build:
      context: .
      dockerfile: ./FlightService/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=flightdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend # connected networks

  hotelservice:
    build:
      context: .
      dockerfile: ./HotelService/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=hoteldb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend # connected networks

  paymentservice:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend # connected networks
  
  frontend:
    build:
      context: .
      dockerfile: ./rsww-front/Dockerfile
    depends_on:
      - apigateway
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  frontend: {}
  backend: {} # network for the rest of communication
