version: '3.8'

services:

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest 
    hostname: 'rabbitmq'
    container_name: 'rabbitmq' 
    ports: 
        - 18439:5672  
        - 18444:15672 
    networks:
      - backend 

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "18772:80"
    depends_on:
      - frontend
      - apigateway
    networks:
      - backend

  apigateway:
    image: szymonk1306/rsww_184394_apigateway:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=userdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend

  tripservice:
    image: szymonk1306/rsww_184394_tripservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=tripdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend

  flightservice:
    image: szymonk1306/rsww_184394_flightservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=flightdb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend 

  hotelservice:
    image: szymonk1306/rsww_184394_hotelservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=hoteldb;Username=postgres;Password=guest;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend 

  paymentservice:
    image: szymonk1306/rsww_184394_paymentservice:latest
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend
  
  frontend:
    image: szymonk1306/rsww_184394_frontend:latest
    depends_on:
      - apigateway
    environment:
      REACT_APP_HOST: 'localhost'
      REACT_APP_PORT: 18772
    networks:
      - backend

networks:
  frontend: {}
  backend: {} 
