version: '3.8'

services:

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    hostname: 'rabbitmq'
    ports:
      - 18439:5672
      - 18444:15672
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "18772:80"
    depends_on:
      - frontend
      - apigateway
    networks:
      - backend

  apigateway:
    image: szymonk1306/rsww_184394_apigateway:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=admin-postgres_db;Port=5432;Database=RSWW_184394_userdb;Username=postgres;Password=student;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend
      - postgres_network

  tripservice:
    image: szymonk1306/rsww_184394_tripservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=admin-postgres_db;Port=5432;Database=RSWW_184394_tripdb;Username=postgres;Password=student;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend
      - postgres_network

  flightservice:
    image: szymonk1306/rsww_184394_flightservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=admin-postgres_db;Port=5432;Database=RSWW_184394_flightdb;Username=postgres;Password=student;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend
      - postgres_network

  hotelservice:
    image: szymonk1306/rsww_184394_hotelservice:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_CONNECTION_STRING: "Host=admin-postgres_db;Port=5432;Database=RSWW_184394_hoteldb;Username=postgres;Password=student;"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend
      - postgres_network

  paymentservice:
    image: szymonk1306/rsww_184394_paymentservice:latest
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
    networks:
      - backend

  frontend:
    image: szymonk1306/rsww_184394_frontend:latest
    depends_on:
      - apigateway
    environment:
      REACT_APP_HOST: 'localhost'
      REACT_APP_PORT: 18772
    networks:
      - backend

networks:
  backend:
    driver: overlay
    name: rsww_184394_backend_network
  postgres_network:
    external: true
    name: admin-postgres_default